all : clean_all
	make -C ./zad1/ all
	make -C ./zad2/ all
	make -C ./zad3a/ all
	make -C ./zad3b/ all

clean:
	make -C ./zad1/ clean
	make -C ./zad2/ clean
	make -C ./zad3a/ clean
	make -C ./zad3b/ clean

clean_all:
	make -C ./zad1/ clean_all
	make -C ./zad2/ clean_all
	make -C ./zad3a/ clean_all
	make -C ./zad3b/ clean_all