all:
	make -C ./zad1/ all
	make -C ./zad2/ all
	make -C ./zad3/ all

clean:
	make -C ./zad1/ clean
	make -C ./zad2/ clean
	make -C ./zad3/ clean

clean_all:
	make -C ./zad1/ clean_all
	make -C ./zad2/ clean_all
	make -C ./zad3/ clean_all