all : clean_all
	make -C ../cw01/zad1/ all
	make -C ../cw01/zad2/ all
	make -C ../cw01/zad3a/ all
	make -C ../cw01/zad3b/ all

clean:
	make -C ../cw01/zad1/ clean
	make -C ../cw01/zad2/ clean
	make -C ../cw01/zad3a/ clean
	make -C ../cw01/zad3b/ clean

clean_all:
	make -C ../cw01/zad1/ clean_all
	make -C ../cw01/zad2/ clean_all
	make -C ../cw01/zad3a/ clean_all
	make -C ../cw01/zad3b/ clean_all